/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ignac
 */
public class JFrame_PORTADA extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_PORTADA
     */
    public JFrame_PORTADA() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPRINCIPAL = new javax.swing.JLabel();
        jLabelBIENVENIDA = new javax.swing.JLabel();
        jButtonSALIR = new javax.swing.JButton();
        jButtonINICIOADMIN = new javax.swing.JButton();
        jButtonINCIO = new javax.swing.JButton();
        jLabelInstruccionSALIR = new javax.swing.JLabel();
        jLabelInstruccionInicio = new javax.swing.JLabel();
        jLabelInstruccionAdmin = new javax.swing.JLabel();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPRINCIPAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/XD.png"))); // NOI18N
        getContentPane().add(logoPRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 390, 140));

        jLabelBIENVENIDA.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabelBIENVENIDA.setText("BIENVENIDOS A ");
        jLabelBIENVENIDA.setToolTipText("");
        getContentPane().add(jLabelBIENVENIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 70));

        jButtonSALIR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSALIR.setText("SALIR");
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 130, 70));

        jButtonINICIOADMIN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonINICIOADMIN.setText("MODO ADMIN");
        jButtonINICIOADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonINICIOADMINActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonINICIOADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 130, 70));

        jButtonINCIO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonINCIO.setText("INICIAR");
        jButtonINCIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonINCIOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonINCIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 130, 70));

        jLabelInstruccionSALIR.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelInstruccionSALIR.setText("-SALIR DEL PROGRAMA:");
        getContentPane().add(jLabelInstruccionSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 260, 50));

        jLabelInstruccionInicio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelInstruccionInicio.setText("-INICIO PARA EL CLIENTE:");
        getContentPane().add(jLabelInstruccionInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 260, 50));

        jLabelInstruccionAdmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelInstruccionAdmin.setText("-INICIO PARA EL ADMINISTRADOR:");
        getContentPane().add(jLabelInstruccionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 310, 50));

        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/27496.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 690, 593));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRActionPerformed
        //SALIR DEL PROGRAMA
        System.exit(0);
    }//GEN-LAST:event_jButtonSALIRActionPerformed

    private void jButtonINICIOADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonINICIOADMINActionPerformed
        //INICIO PARA EL ADMINISITRADOR
        JFrame_INICIOADMIN aux = new JFrame_INICIOADMIN();
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonINICIOADMINActionPerformed

    private void jButtonINCIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonINCIOActionPerformed
        //INICIO PARA TODO PUBLICO
        JFrame_INICIO a = null;
        try {
            a = new JFrame_INICIO();
        } catch (Exception ex) {
            Logger.getLogger(JFrame_PORTADA.class.getName()).log(Level.SEVERE, null, ex);
        }
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonINCIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_PORTADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_PORTADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_PORTADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_PORTADA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_PORTADA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonINCIO;
    private javax.swing.JButton jButtonINICIOADMIN;
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JLabel jLabelBIENVENIDA;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelInstruccionAdmin;
    private javax.swing.JLabel jLabelInstruccionInicio;
    private javax.swing.JLabel jLabelInstruccionSALIR;
    private javax.swing.JLabel logoPRINCIPAL;
    // End of variables declaration//GEN-END:variables
}
