/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CODIGO.Administrador;
import CODIGO.CSVCode;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ignac
 */
public class JFrame_INICIOADMIN extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrame_INICIOADMIN
     */
    public JFrame_INICIOADMIN() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private boolean IniciarSesion(String user, String pass) throws Exception{
        ArrayList<Administrador> listaAdmin = new ArrayList();
        listaAdmin = CSVCode.cargarAdmin();
        
        for (Administrador admin : listaAdmin){
            if (admin.getUser().equals(user)){
                return admin.getPassword().equals(pass);                                  
            }
        }
     return false;      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLOGOUSER = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        jLabelUSER = new javax.swing.JLabel();
        jLabelPASSWORD = new javax.swing.JLabel();
        jButtonENTRAR = new javax.swing.JButton();
        jButtonATRAS = new javax.swing.JButton();
        jButtonSALIR = new javax.swing.JButton();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLOGOUSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intento.png"))); // NOI18N
        getContentPane().add(jLabelLOGOUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 180, 200));

        USER.setText("admin");
        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });
        getContentPane().add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 220, 60));

        PASSWORD.setText("123");
        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });
        getContentPane().add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 220, 60));

        jLabelUSER.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelUSER.setText("USER:");
        getContentPane().add(jLabelUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 140, 40));

        jLabelPASSWORD.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelPASSWORD.setText("PASSWORD:");
        getContentPane().add(jLabelPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 160, 50));

        jButtonENTRAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonENTRAR.setText("ENTRAR");
        jButtonENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonENTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 110, 50));

        jButtonATRAS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonATRAS.setText("ATRÁS");
        jButtonATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATRASActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 50));

        jButtonSALIR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSALIR.setText("SALIR");
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 100, 50));

        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/27496.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRActionPerformed
        // SALIR DEL PROGRAMA
        System.exit(0);
    }//GEN-LAST:event_jButtonSALIRActionPerformed
    
    private void jButtonENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENTRARActionPerformed
        // INICIO SESION A MENU                
        String user = new String(USER.getText());
        String pass = new String(PASSWORD.getPassword());
                
        try {
            if (IniciarSesion(user, pass)){
                
                MENU_ADMIN aux = new MENU_ADMIN();
                aux.setVisible(true);
                dispose();
            }
            
            else
                JOptionPane.showMessageDialog(this, "Usuario y/o Contrasena incorrecta");
        } catch (Exception ex) {
            Logger.getLogger(JFrame_INICIOADMIN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonENTRARActionPerformed

        
    private void jButtonATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATRASActionPerformed
        // ATRAS AL PROGRAMA
        JFrame_PORTADA aux = new JFrame_PORTADA();
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonATRASActionPerformed

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIOADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIOADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIOADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIOADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_INICIOADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JTextField USER;
    private javax.swing.JButton jButtonATRAS;
    private javax.swing.JButton jButtonENTRAR;
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelLOGOUSER;
    private javax.swing.JLabel jLabelPASSWORD;
    private javax.swing.JLabel jLabelUSER;
    // End of variables declaration//GEN-END:variables
}
