/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CODIGO.CSVCode;
import CODIGO.ComboItems;
import CODIGO.Region;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ignac
 */
public class JFrame_INICIO extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_INICIO
     */
    public JFrame_INICIO() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
                    
        //METODOS DE COMBOBOX MENU---------------------
        jComboBoxREGIONES.removeAllItems();
        ArrayList<Region> lista = new ArrayList();
        lista = CSVCode.cargarRegiones();
        
        for (Region item : lista){
         //System.out.println(item.getNombre());
          model.addElement(new ComboItems(item.getNombre(), item.getId()));
        }
        jComboBoxREGIONES.setModel(model); 
 
    }
    
       
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLOGOMAPA = new javax.swing.JLabel();
        jLabelMENU = new javax.swing.JLabel();
        SeleccionarRegion = new javax.swing.JButton();
        jComboBoxREGIONES = new javax.swing.JComboBox<>();
        MostrarALL_EVENTOS = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        ATRAS = new javax.swing.JButton();
        MostrarALL_REGIONES = new javax.swing.JButton();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLOGOMAPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regiones_1.jpg"))); // NOI18N
        getContentPane().add(jLabelLOGOMAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 280, 510));

        jLabelMENU.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelMENU.setText("MENÚ");
        getContentPane().add(jLabelMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 120, 60));

        SeleccionarRegion.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        SeleccionarRegion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        SeleccionarRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarRegionActionPerformed(evt);
            }
        });
        getContentPane().add(SeleccionarRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 40, 40));

        jComboBoxREGIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxREGIONESActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxREGIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 160, 40));

        MostrarALL_EVENTOS.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        MostrarALL_EVENTOS.setText("MOSTRAR TODOS LOS EVENTOS");
        MostrarALL_EVENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarALL_EVENTOSActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarALL_EVENTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 210, 60));

        SALIR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 110, 60));

        ATRAS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ATRAS.setText("ATRÁS");
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });
        getContentPane().add(ATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 190, 60));

        MostrarALL_REGIONES.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        MostrarALL_REGIONES.setText("MOSTRAR TODAS LAS REGIONES");
        MostrarALL_REGIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarALL_REGIONESActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarALL_REGIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 210, 60));

        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/27496.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarRegionActionPerformed
        // TODO add your handling code here: 
        Object item = jComboBoxREGIONES.getSelectedItem();
        //JOptionPane.showMessageDialog(this,((ComboItems)item).getValue());
        
        String idRegion = ((ComboItems)item).getValue();
        //System.out.println(idRegion);
        
        EventosRegionSelect aux = null;
        try {
            aux = new EventosRegionSelect(idRegion);
        } catch (Exception ex) {
            Logger.getLogger(JFrame_INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SeleccionarRegionActionPerformed

    private void MostrarALL_EVENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarALL_EVENTOSActionPerformed
        // TODO add your handling code here:
        MENU_AllEventos aux = null;
        try {
            aux = new MENU_AllEventos ();
        } catch (Exception ex) {
            Logger.getLogger(JFrame_INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MostrarALL_EVENTOSActionPerformed

    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        // ATRAS AL PROGRAMA
        JFrame_PORTADA aux = new JFrame_PORTADA();
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ATRASActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        //SALIR DEL PROGRAMA
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void jComboBoxREGIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxREGIONESActionPerformed
        //REGIONES
    }//GEN-LAST:event_jComboBoxREGIONESActionPerformed

    private void MostrarALL_REGIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarALL_REGIONESActionPerformed
        // TODO add your handling code here:
        MENU_ALLRegiones aux = null;
        try {
            aux = new MENU_ALLRegiones();
        } catch (Exception ex) {
            Logger.getLogger(JFrame_INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MostrarALL_REGIONESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrame_INICIO().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(JFrame_INICIO.class.getName()).log(Level.SEVERE, null, ex);
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRAS;
    private javax.swing.JButton MostrarALL_EVENTOS;
    private javax.swing.JButton MostrarALL_REGIONES;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton SeleccionarRegion;
    private javax.swing.JComboBox<String> jComboBoxREGIONES;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelLOGOMAPA;
    private javax.swing.JLabel jLabelMENU;
    // End of variables declaration//GEN-END:variables
}
