/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CODIGO.CSVCode;
import CODIGO.Eventos;
import CODIGO.Region;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ignac
 */
public class MENU_AllEventos extends javax.swing.JFrame {
    TableRowSorter trs;
    DefaultTableModel tDatos = new DefaultTableModel();
    /**
     * Creates new form MENU_AllEventos
     * @throws java.lang.Exception
     */
    public MENU_AllEventos() throws Exception{
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarDatos_Eventos();

    }
    
    public void MostrarDatos_Eventos() throws Exception{
        
        tDatos.addColumn("IdEvento");
        tDatos.addColumn("Nombre");
        tDatos.addColumn("Fecha_Evento");
        TablaEventos.setModel(tDatos);
        
        String [] datos = new String [3];
        
        try{
            ArrayList<Eventos> lista = new ArrayList();
            lista = CSVCode.cargarEventos();
            
            for (Eventos item : lista){
                datos[0] = Integer.toString(item.getIdEventos());
                datos[1] = item.getName();
                datos[2] = item.getFecha_Evento();
                tDatos.addRow(datos);
            }
            TablaEventos.setModel(tDatos);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "No hay eventos en la data base");
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEventos = new javax.swing.JTable();
        ATRAS = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        TEXTO = new javax.swing.JLabel();
        jTextFILTRO = new javax.swing.JTextField();
        REPORTE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        TablaEventos.setEnabled(false);
        jScrollPane1.setViewportView(TablaEventos);
        if (TablaEventos.getColumnModel().getColumnCount() > 0) {
            TablaEventos.getColumnModel().getColumn(1).setResizable(false);
        }

        ATRAS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ATRAS.setText("ATRÁS");
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });

        SALIR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        TEXTO.setText("Filtrar:");

        jTextFILTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFILTROActionPerformed(evt);
            }
        });
        jTextFILTRO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFILTROKeyTyped(evt);
            }
        });

        REPORTE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        REPORTE.setText("REPORTE");
        REPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ATRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(TEXTO, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFILTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(REPORTE)
                .addGap(18, 18, 18)
                .addComponent(SALIR))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ATRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTO, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextFILTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REPORTE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        JFrame_INICIO aux = null;
        try {
            aux = new JFrame_INICIO();
        } catch (Exception ex) {
            Logger.getLogger(MENU_AllEventos.class.getName()).log(Level.SEVERE, null, ex);
        }
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ATRASActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void jTextFILTROKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFILTROKeyTyped
        // TODO add your handling code here:
        //jTextFILTRO.addKeyListener(l);
    }//GEN-LAST:event_jTextFILTROKeyTyped

    private void jTextFILTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFILTROActionPerformed
        // TODO add your handling code here:

        
        jTextFILTRO.addKeyListener(new KeyAdapter(){
        public void KeyRealesed(KeyEvent ke){
            trs.setRowFilter(RowFilter.regexFilter(jTextFILTRO.getText(), 0));
        }
        });
        trs = new TableRowSorter(tDatos);
        TablaEventos.setRowSorter(trs);
    }//GEN-LAST:event_jTextFILTROActionPerformed

    private void REPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTEActionPerformed
        // TODO add your handling code here:
        ArrayList<Eventos> lista = new ArrayList();
        try {
            lista = CSVCode.reporteEvento();
            JOptionPane.showMessageDialog(null, "Reporte exitoso");
        } catch (Exception ex) {
            Logger.getLogger(MENU_ALLRegiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_REPORTEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_AllEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_AllEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_AllEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_AllEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MENU_AllEventos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MENU_AllEventos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRAS;
    private javax.swing.JButton REPORTE;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel TEXTO;
    private javax.swing.JTable TablaEventos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFILTRO;
    // End of variables declaration//GEN-END:variables
}
