/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CODIGO.Administrador;
import CODIGO.CSVCode;
import CODIGO.Eventos;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ignac
 */
public class MENU_ADDADMIN extends javax.swing.JFrame {
    DefaultTableModel tDatos = new DefaultTableModel();
    String accion = "nuevo";
    /**
     * Creates new form MENU_ADDADMIN
     */
    public MENU_ADDADMIN() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarDatos_Admin();
    }
    
    public void MostrarDatos_Admin() throws Exception{
        
        tDatos.addColumn("User");
        tDatos.addColumn("Pass");
        TablaAdmin.setModel(tDatos);
        
        String [] datos = new String [2];
        
        try{
            ArrayList<Administrador> listaAdmin = new ArrayList();
            
            listaAdmin = CSVCode.cargarAdmin();

            for (Administrador item : listaAdmin){

                datos[0] = item.getUser();
                datos[1] = item.getPassword();
                tDatos.addRow(datos);
            }
            
            TablaAdmin.setModel(tDatos);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "No hay administradores en la data base");
        }
           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ATRAS = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        NUEVO = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        TextUser = new javax.swing.JTextField();
        TextPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAdmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ATRAS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ATRAS.setText("ATRAS");
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });
        getContentPane().add(ATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 50));

        CANCELAR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });
        getContentPane().add(CANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 50));

        GUARDAR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GUARDAR.setText("GUARDAR");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 130, 70));

        NUEVO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NUEVO.setText("NUEVO");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(NUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, 40));

        EDITAR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EDITAR.setText("EDITAR");
        EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARActionPerformed(evt);
            }
        });
        getContentPane().add(EDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 120, 40));

        ELIMINAR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });
        getContentPane().add(ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 120, 40));
        getContentPane().add(TextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 280, 50));
        getContentPane().add(TextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 280, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("MENU ADMINISTRADORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 370, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("USER NUEVO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD NUEVO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, 50));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/27496.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 470));

        TablaAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaAdmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, -3, 290, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        // TODO add your handling code here:
        MENU_ADMIN aux = new MENU_ADMIN();
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ATRASActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        JFrame_PORTADA aux = new JFrame_PORTADA();
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CANCELARActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
        String [] datos = new String [2];
        CSVCode miBD= new CSVCode(0," ");
        
        if (this.accion=="nuevo"){
            try {
                if (miBD.newAdmin(TextUser.getText(),TextPass.getText())){
                    JOptionPane.showMessageDialog(this, "Guardado con exito");
                    datos[0] = TextUser.getText();
                    datos[1] = TextPass.getText();
                    tDatos.addRow(datos);
                }else
                    JOptionPane.showMessageDialog(this, "Error al guardar");
            } catch (IOException ex) {
                Logger.getLogger(MENU_ADDADMIN.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(MENU_ADDADMIN.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(this.accion=="editar"){
            //System.out.println("estoy en editar");
            int fila = TablaAdmin.getSelectedRow();
            tDatos.setValueAt(TextUser.getText(), fila, 0);
            tDatos.setValueAt(TextPass.getText(), fila, 1);
            
            try {
                miBD.editAdmin(TextUser.getText(),TextPass.getText());
            } catch (Exception ex) {
                Logger.getLogger(MENU_ADDEVENTOS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
        
    }//GEN-LAST:event_GUARDARActionPerformed

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
        // TODO add your handling code here:
        String [] datos = new String [2];
        CSVCode miBD = new CSVCode(0," ");
        int fila = TablaAdmin.getSelectedRow();
        this.accion= "editar";
        //System.out.println(tDatos.getValueAt(fila, 0));
        //System.out.println(tDatos.getValueAt(fila, 1));
        //System.out.println(tDatos.getValueAt(fila, 2));
        
        TextUser.setText((String) tDatos.getValueAt(fila, 0));
        TextPass.setText((String) tDatos.getValueAt(fila, 1));  
    }//GEN-LAST:event_EDITARActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here:
        this.accion="nuevo";
        TextUser.setText("");
        TextPass.setText("");
    }//GEN-LAST:event_NUEVOActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        // TODO add your handling code here:
        String [] datos = new String [2];
        CSVCode miBD = new CSVCode(0," ");
        int fila = TablaAdmin.getSelectedRow();
        /*/
        System.out.println(tDatos.getValueAt(fila, 0));
        System.out.println(tDatos.getValueAt(fila, 1));
        System.out.println(tDatos.getValueAt(fila, 2));
        /*/
        String idAdminStr = (String) tDatos.getValueAt(fila, 0);
        int idEvento = Integer.parseInt(idAdminStr);
        if(fila>=0){
            tDatos.removeRow(fila);
            try {
                miBD.removeEventos(idEvento);
            } catch (Exception ex) {
                Logger.getLogger(MENU_ADDEVENTOS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un evento en la tabla");
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MENU_ADDADMIN().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MENU_ADDADMIN.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRAS;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton EDITAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JButton NUEVO;
    private javax.swing.JTable TablaAdmin;
    private javax.swing.JTextField TextPass;
    private javax.swing.JTextField TextUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
